# Generated by Django 5.1.1 on 2024-10-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='contacto',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='requisitos',
            field=models.TextField(null=True),
        ),
    ]
