# Generated by Django 5.1.2 on 2024-10-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voluntarios', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='oportunidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='voluntariados/'),
        ),
    ]
